syntax = "proto3";

option java_package = "com.jonipharju.less.launcher.proto";
option java_multiple_files = true;

message LauncherUserData {
  repeated StoredFavorite favorites = 1;
  LauncherSettings settings = 2;
}

message StoredFavorite {
  string package_name = 1;
  string activity_name = 2;
  int64 profile_serial_number = 3;
  int32 position = 4;
  optional string custom_label = 5;
}

message LauncherSettings {
  optional IconMode icon_mode_override = 1;
  DrawerOpenDirection drawer_open_direction = 2;
  HomeAlignment home_alignment = 3;
  optional bool opens_keyboard_with_drawer = 4;
  optional string theme_id = 5;
}

enum IconMode {
  ICON_MODE_UNSPECIFIED = 0;
  ICON_MODE_ORIGINAL = 1;
  ICON_MODE_TINTED = 2;
  ICON_MODE_OFF = 3;
}

enum DrawerOpenDirection {
  DRAWER_OPEN_DIRECTION_UNSPECIFIED = 0;
  DRAWER_OPEN_DIRECTION_SWIPE_UP = 1;
  DRAWER_OPEN_DIRECTION_SWIPE_DOWN = 2;
}

enum HomeAlignment {
  HOME_ALIGNMENT_UNSPECIFIED = 0;
  HOME_ALIGNMENT_LEFT = 1;
  HOME_ALIGNMENT_CENTRED = 2;
}
